### ISSUE TITLE
Error loading /config/configuration.yaml: mapping values are not allowed here   in "/config/packages/battery_alert.yaml", line 444, column 86

### ISSUE THREAD

**Issue by jalme** [notoriousbdg/Home-AssistantConfig#10]
Hi,

Following the configuration instructions for battery_alert package can't get passed the error after adding the packages section in config.yaml

Regards.

**Comment by notoriousbdg** [comment]
Can you show me what the homeassistant: section of configuration.yaml looks like?  Also, how did you save the yaml file? It's best to use the raw link.
