### ISSUE TITLE
configuration variable "json_attributes" is deprecated, replace with "json_attributes_topic"

### ISSUE THREAD

**Issue by TheZoker** [notoriousbdg/Home-AssistantConfig#11]
Some recent changes in HA and this custom script causing the following issue in the logs:
```configuration variable "json_attributes" is deprecated, replace with "json_attributes_topic"```

More information:
https://github.com/home-assistant/home-assistant/pull/19223

Code probably causing the issue:
https://github.com/notoriousbdg/Home-AssistantConfig/blob/master/packages/battery_alert.yaml#L583

**Comment by tonnie84** [comment]
I have also the same problem

Homeassistant 0.85.0
package 1.1.6

**Comment by notoriousbdg** [comment]
Fixed in https://github.com/notoriousbdg/Home-AssistantConfig/commit/071cff6857a37920fb363bcb2c6ea5b31e080dd3
