### ISSUE TITLE
Suggestion Automation for adding to view with Lovelace

### ISSUE THREAD

**Issue by Landrash** [notoriousbdg/Home-AssistantConfig#12]
With the release of HA 0.86 Lovelace will be the default. By default there's no way of showing all the items in a group.

Having an automation to update a view might be one option or an example Lovelace card.

**Comment by notoriousbdg** [comment]
I just upgraded to 0.86.1 and the Battery Status group works fine for me with no changes to the package.  The only difference I see from pre-lovelace is that it now requires a browser refresh.

**Comment by Landrash** [comment]
@notoriousbdg Are you showing the group using the old state view or by using Lovelace?

**Comment by notoriousbdg** [comment]
I'm using the default system managed Lovelace UI without any customizations.

**Comment by notoriousbdg** [comment]
Check out post https://community.home-assistant.io/t/howto-create-battery-alert-without-creating-a-template-for-every-device/30576/608 for an example.
