### ISSUE TITLE
help

### ISSUE THREAD

**Issue by superbosu** [notoriousbdg/Home-AssistantConfig#15]
Hi,
I tried to copy and paste your package file in my HA but when I tried to check it a lot of errors comes out.
Is something that I have to change inside the battery_alert.yaml file ?
tnx

**Comment by notoriousbdg** [comment]
Try using the raw link to copy/pasted from.

**Comment by superbosu** [comment]
done... copy and paste as RAW:

Invalid config for [automation]: Invalid platform specified @ data['trigger'][0]. Got None. (See /config/configuration.yaml, line 99). Please check the docs at https://home-assistant.io/components/automation/
Invalid config for [automation]: Invalid platform specified @ data['trigger'][0]. Got None. (See /config/configuration.yaml, line 99). Please check the docs at https://home-assistant.io/components/automation/
Invalid config for [automation]: Invalid platform specified @ data['trigger'][1]. Got None. (See /config/configuration.yaml, line 99). Please check the docs at https://home-assistant.io/components/automation/

I don't know if I have to change someting from the file in order to get it work.

**Comment by notoriousbdg** [comment]
Which version of Home Assistant are you running?  The latest version only works with 0.86.x due to a breaking change in that version.
