### ISSUE TITLE
Entity ID  is an invalid entity

### ISSUE THREAD

**Issue by dcava** [notoriousbdg/Home-AssistantConfig#16]
Hi,

Anyone noticed issues since the upgrade to home-assistant 0.87 with errors like the following:

`ERROR (MainThread) [homeassistant.components.automation] Error while executing automation automation.update_battery_status_group_members. Invalid data for call_service at pos 1: Entity ID  is an invalid entity id for dictionary value @ data['entities']`

None of the previous auto-created sensor.battery_* are created show up in the battery status panel.

I wonder if it's something to do with the new entity registry?

MQTT broker still seems to be publishing correct information...

David

**Comment by notoriousbdg** [comment]
That can happen on startup if the automation runs before battery sensors have been created.  I believe https://github.com/notoriousbdg/Home-AssistantConfig/commit/f25258bfff8546f4b57d8303328a3902da7050d7 will prevent that from happening.  Can you try updating to the latest version and let me know if you still see the error?

**Comment by dcava** [comment]
Beauty, all fixed. Thanks!
