### ISSUE TITLE
Config errors

### ISSUE THREAD

**Issue by andrkaz** [notoriousbdg/Home-AssistantConfig#17]
Home assistant version 0.88.1. 

Invalid config for [automation]: required key not provided @ data['action']. Got None required key not provided @ data['trigger']. Got None. (See ?, line ?). Please check the docs at https://home-assistant.io/components/automation/

How repair it?

**Comment by Beduir** [comment]
I had such problem. I downloaded the file again. Maybe the file was damaged. It is necessary to use the "Raw" button.

**Comment by andrkaz** [comment]
I try to downlodad again, also try create empty file and copy/paste code - nothing happens, errors

**Comment by andrkaz** [comment]
I found bug. In "configuration.yaml" I dont comment this line:
automation: !include automations.yaml
After commenting this with "#" all work

**Comment by notoriousbdg** [comment]
Home Assistant doesn't like an empty automations.yaml when using a package that has automations in it.  Adding an automation to automations.yaml is another way to workaround the issue.
