### ISSUE TITLE
Ikea tradfri Simple dimmer battery status is not showing

### ISSUE THREAD

**Issue by jodur** [notoriousbdg/Home-AssistantConfig#8]
I have 2 tradfri remote.
1 [Wireless dimmer](https://www.ikea.com/gb/en/products/lighting/smart-lighting/tr%C3%A5dfri-wireless-dimmer-white-art-00347831/)
2 [Remote control](https://www.ikea.com/gb/en/products/lighting/smart-lighting/tr%C3%A5dfri-remote-control-art-30338849/l)

The battery sensor for the remote control is created and showing up. The battery for for the wireless dimmer is not showing up.

The Wireless dimmer is in the entity list of home assistant

'''

sensor.tradfri_wireless_dimmer | 87 | battery_level: 87 model_number: TRADFRI wireless dimmer power_source: Battery manufacturer: IKEA of Sweden firmware_version: 1.2.248 serial:  friendly_name: TRADFRI wireless dimmer unit_of_measurement: %
-- | -- | --

'''

**Comment by notoriousbdg** [comment]
It's odd that the state matches the battery_level attribute.  If the state represents the battery level, you can use customize to set device_class to battery. and the package will treat it as a battery.

```yaml
sensor.tradfri_wireless_dimmer:
  device_class: battery
```

If the state doesn't represent the battery level, then try forcing a state change on the device or just wait for it to report in.

**Comment by jodur** [comment]
The Remote control has the same, state matches the battery_level attribute, however this battery is picked up by you package automaticly. Will try your suggestion to modify the customize


'''

sensor.tradfri_remote_control | 74 | battery_level: 74 model_number: TRADFRI remote control power_source: Battery manufacturer: IKEA of Sweden firmware_version: 1.2.214 serial:  friendly_name: TRADFRI remote control unit_of_measurement: %
-- | -- | --



'''
